### ISSUE TITLE
validateMemObject

### ISSUE THREAD

**Issue by jpola** [clMathLibraries/clSPARSE#13]
Create a nice function which take *Private class and validate the  underneath buffer which might be void* for CL20, and cl_mem for lower versions

**Comment by jlgreathouse** [comment]
Same question as #14  -- can this be closed now?  The one thing we're missing for both of these is a test for OpenCL 2.0 SVM. We currently always return success in this case.

**Comment by jlgreathouse** [comment]
@jpola -- thoughts?

**Comment by jpola** [comment]
I agree, let the internal code of the validation procedures be disabled in
the Release mode

2015-10-15 6:58 GMT+02:00 Joseph Greathouse <notifications@github.com>:

**Comment by kvaragan** [comment]
If the validation procedure is only happening in I/O and not inside the actual function call, then I think this validation should be present in the Release mode as well. Validations can go wrong in release mode as well.

**Comment by jpola** [comment]
They should be present in all interface functions.

2015-10-16 12:44 GMT+02:00 Kiran <notifications@github.com>:

**Comment by kknox** [comment]
The overwhelming feedback I have received from our other libraries, is that users do not like to see 'extra' calls into the opencl runtime even if the performance impact is negligible.  Users will often take traces of their opencl application, and question why so many calls to clGetMemObjectInfo, clGetDeviceInfo or clGetCommandqueueInfo exists.  This is fine for a debug build, but in a release build users want these optimized out and see clEnqueueNDRange.

Honestly, in rare cases that a user has a bug only reproducible in a release build, they can manually enable the sanity checks back into the release build themselves; a benefit of being an open source library.
