### ISSUE TITLE
Does not build on OS X

### ISSUE THREAD

**Issue by treasurebox** [clMathLibraries/clSPARSE#139]
Hi!

  Can't seem to build on OS X (Yosemite). I do a 'cmake .', then make, I get:

```
'OpenCL/cl.hpp' file not found
#include <OpenCL/cl.hpp>
```

Any quick workaround?

**Comment by kknox** [comment]
Hi @treasurebox 
Yes, Yosemite does not appear to ship with the cl.hpp file.  I also had to tackle this problem when I was working on our Travis automation.  Take a look at how I fix this in [the .travis.yml install: section](https://github.com/clMathLibraries/clSPARSE/blob/master/.travis.yml) by using wget to download the header from khronos website.

**Comment by treasurebox** [comment]
Yes, that did the trick, thanks!

**Comment by treasurebox** [comment]
Hi!

  Don't want to nitpick, but I think this issue still should be open, at least some clear instruction about this in the README would be nice.
  Other note is that downloading the header file in /System/Library/... is not very nice, and in all likeliness it won't work on next OS X version (10.11 'El Capitan') because of security feature 'rootless' which prevents writing to system directories, so dowloading cl.hpp to the build directory (or simply putting it in the clSPARSE src distribution) might be a simpler option.

All the best!

**Comment by pavanky** [comment]
@treasurebox Looks like `cl.hpp` may be added to the repo itself in the future which will solve the issue: https://github.com/clMathLibraries/clSPARSE/issues/120

**Comment by treasurebox** [comment]
Cool, Thanks!

**Comment by dpo** [comment]
The `cl.hpp` referred to in `.travis.yml` no longer exists on the Krhonos website. Is it safe to use [this one](https://www.khronos.org/registry/cl/api/2.1/cl.hpp)? It's in the 2.1 folder, but it seems to indicate it's for OpenCL 1.0, 1.1 and 1.2.

**Comment by kknox** [comment]
Yes, I believe it is safe to use.  Looks like the one that disappeared is version 1.2.7, and the new one is version 1.2.8.  Why they changed the path to the file, I don't know.  It does look like they incorporated some bug fixes, but nothing that should break our functionality.

**Comment by dpo** [comment]
Thanks.
