### ISSUE TITLE
validateMemSize

### ISSUE THREAD

**Issue by jpola** [clMathLibraries/clSPARSE#14]
Create functions for validating *Private classes buffers concerning size of allocated space.

**Comment by jlgreathouse** [comment]
Should this issue be closed? It looks like the work in #145 handles both of these requests.

**Comment by kknox** [comment]
Certainly my comment about validating in debug builds is taken care of.  I leave it to @jpola to determine if the original issue about *private classes is done.

**Comment by jpola** [comment]
:+1:
