### ISSUE TITLE
clSPARSE-xx.h not visible in project explorer

### ISSUE THREAD

**Issue by jpola** [clMathLibraries/clSPARSE#143]
Is it intended this file to be hidden?
OS: Linux, IDE: QtCreator

**Comment by kknox** [comment]
No, it should not be hidden (I think it's a public file).  I think the reason it's missing is that it's not listed in the [cmake](https://github.com/clMathLibraries/clSPARSE/blob/master/src/library/CMakeLists.txt#L140) file.

**Comment by jpola** [comment]
Yes, that is the reason. I just didn't know if that is just a minor mistake.

**Comment by kknox** [comment]
Sorry, only forgetfulness.  In general, I don't see a reason to leave any file outside of the IDE, so if others are missing, assume the cmake file was not updated with the introduction of the new file.  Obviously, .cpp files are easy to catch but .hpp files can sneakily remain hidden without error.
