### ISSUE TITLE
clSPARSE - Build fails in Mac OS X Yosemite

### ISSUE THREAD

**Issue by kvaragan** [clMathLibraries/clSPARSE#151]
First error I get 'OpenCL/cl.hpp' file not found, I replaced 'cl.hpp' with  opencl.h.
As a result I get another error "use of undeclared identifier 'cl'    cl::Event event;" . Any idea how to fix this.

Platform: Macbook pro - MAC OS X Yosemite supports OpenCL 1.2.

**Comment by pavanky** [comment]
You need to undo what you did and download the proper cl.hpp and put it somewhere in the system path. You can find the cl.hpp file over here: https://www.khronos.org/registry/cl/api/1.2/cl.hpp

**Comment by kknox** [comment]
@kvaragan Look at #139 .
