### ISSUE TITLE
make install not working

### ISSUE THREAD

**Issue by dagamayank** [clMathLibraries/clSPARSE#193]
After compiling with `make` if I to do `make install` I get the following error:

```
make: *** No rule to make target `install'.  Stop.
```

`make` completes fine with zero errors. This occurs on both master and develop branches.

**Comment by aaamourao** [comment]
@dagamayank did you find out a workaround?

**Comment by kknox** [comment]
clSparse uses a 'super-build' build framework, so you need to `cd clSPARSE-package` and run `make install` using the makefile generated for the library.  The root level makefile has no install target
