### ISSUE TITLE
Wrong system size checks?

### ISSUE THREAD

**Issue by TillAlex** [clMathLibraries/clSPARSE#204]
When starting a solver the following parameter check is done

[`if( ( pA->num_cols != pB->num_values ) || ( pA->num_rows != pX->num_values ) )
    {
        return clsparseInvalidSystemSize;
    }`](https://github.com/clMathLibraries/clSPARSE/blob/master/src/library/solvers/conjugate-gradients.hpp#L59)

(Same in [bi-conjugate solver](https://github.com/clMathLibraries/clSPARSE/blob/master/src/library/solvers/biconjugate-gradients-stabilized.hpp#L52))

From my understanding the number of columns of A should match the number of elements of x while the number of rows matches the number of elements of b.

This corresponds to what is done in the samples. There the sizes are defined like this:
[` x.num_values = A.num_cols;`](https://github.com/clMathLibraries/clSPARSE/blob/master/samples/sample-cg.cpp#L209) and [`b.num_values = A.num_rows`](https://github.com/clMathLibraries/clSPARSE/blob/master/samples/sample-cg.cpp#L218).

Am I missing something?

**Comment by kknox** [comment]
Can you link to the library code and the sample code you reference above?

**Comment by TillAlex** [comment]
You can find the links in the first post now.

**Comment by TillAlex** [comment]
Attached you find a patch fixing the solvers for non square matrices:

[SystemSizePatch.zip](https://github.com/clMathLibraries/clSPARSE/files/757751/SystemSizePatch.zip)

**Comment by kknox** [comment]
You may not be familiar with github, but do you know how to submit code [through a PR](https://help.github.com/articles/about-pull-requests/)?  If not, i'll try to get this patch merged manually sometime this week.
