### ISSUE TITLE
From clsparse<Vector><Scalar>Private to clsparse::vector<T>

### ISSUE THREAD

**Issue by jpola** [clMathLibraries/clSPARSE#48]
Hi,
currently I'm working on clsparse::vector class which might help us to simplify the code and hide differences between cl1.2 and cl2.0 implementations. I would like to know your opinion about the idea of substituting *Private structures with the clsparse::vector class. If we will have clsparse::vector I don't see the need for the *Private classes to exists. If we want to keep both structures, for all algorithm I will have to write proper specialisations which actually will differ in very little details like passing buffer to kernel. I would like to avoid this unnecessary duplication. The clsparse::vector class is very simple now but is enough, in my opinion, to substitute *Private structures.

pros: 
- unify the code,
- unify the way to pass the buffers to kernels,
- manages memory for internal buffers.
- clsparse::vector == clsparseVectorPrivate
- clsparse::vector[1] == clsprseScalarPrivate
- easy to use
- hides the cl1.2 and cl2.0 differences.
- good base line to extend this class for other algorithm requirements (iterators)

cons: 
- don't know yet if that will interfere with the C interface. I think it will not for the moment.
- not quite an issue but a all algorithms need to be refractored.

What is your opinion?

**Comment by jpola** [comment]
The clsparse::vector and array are already present in the code. In every iteration I see the progress where the clsparse::vector is overtaking the *Private concept.

**Comment by kknox** [comment]
Yes, and this is a good thing.  If we could eventually eliminate the *Private and the memmapRAII classes, clsparse becomes simpler to maintain.  With respect to your question in #138, bolt::device_vector would potentially replace clsparse::vector.
