### ISSUE TITLE
Cloud-based automated builds

### ISSUE THREAD

**Issue by kknox** [clMathLibraries/clSPARSE#78]
When clSPARSE is open to the public, integrate the services of [Travis](https://travis-ci.org/) and [Appveyor](http://www.appveyor.com/) to utilize their services for pull-requests.  That should also allow us to integrate build badges on our main readme file for the site.

**Comment by jpola** [comment]
Do you think that we might run some tests with Travis after the build step? I think it might be tricky since we need to download some matrices for blas2, blas3 and solver tests.

**Comment by kknox** [comment]
For sure!  I would like to get CI to run at least a minimal test suite on every PR and check-in.  A few things we have to consider first.  I think our superbuild infrastructure we can leverage to download sparse matrices on the fly.  We have to make sure that we keep the test wall time reasonable.  We don't want to wait too long for tests to complete on a PR.  The tricky part is opencl; there are no guarantees what sort of devices a VM will expose.  Most likely only CPU devices, but I'm curious what opencl will detect in Travis's docker infrastructure.  We probably need to enhance the functionality of program_options in our test and bench programs so that we can script exactly what tests to run on exactly the devices we choose.

**Comment by jpola** [comment]
Ah, I totally forgot that we focused only on GPU. Before running tests
using travis we have to test our solution with CPU which I've never done.

2015-08-21 19:16 GMT+02:00 Kent Knox <notifications@github.com>:

**Comment by kknox** [comment]
PR #130 closes this issue
